steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: "bash"
    args: 
      -"-c"
      - |
        echo subvar is ${_SUBVAR}

    timeout: 300s
    options:
      substitution_option: "ALLOW_LOOSE"

